theme: jekyll-theme-minimal
title: Parkeo!
description: Aplicación para usuarios y personal del parqueo FIUSAC, proyecto de tesis de la carrera de Ingeniería en Ciencias y Sistemas de la Universidad de San Carlos de Guatemala. 
